//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Library")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LibraryClient.ServiceReference.BookInfo BookInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LibraryClient.ServiceReference.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibraryClient.ServiceReference.BookInfo BookInfo {
            get {
                return this.BookInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BookInfoField, value) != true)) {
                    this.BookInfoField = value;
                    this.RaisePropertyChanged("BookInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibraryClient.ServiceReference.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookInfo", Namespace="http://schemas.datacontract.org/2004/07/Library")]
    [System.SerializableAttribute()]
    public partial class BookInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Library")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookID {
            get {
                return this.BookIDField;
            }
            set {
                if ((this.BookIDField.Equals(value) != true)) {
                    this.BookIDField = value;
                    this.RaisePropertyChanged("BookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Stan {
            get {
                return this.StanField;
            }
            set {
                if ((this.StanField.Equals(value) != true)) {
                    this.StanField = value;
                    this.RaisePropertyChanged("Stan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookExceptions", Namespace="http://schemas.datacontract.org/2004/07/Library")]
    [System.SerializableAttribute()]
    public partial class BookExceptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listOfBooks", ReplyAction="http://tempuri.org/IService1/listOfBooksResponse")]
        LibraryClient.ServiceReference.Book[] listOfBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listOfBooks", ReplyAction="http://tempuri.org/IService1/listOfBooksResponse")]
        System.Threading.Tasks.Task<LibraryClient.ServiceReference.Book[]> listOfBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/connectToLibrary", ReplyAction="http://tempuri.org/IService1/connectToLibraryResponse")]
        int connectToLibrary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/connectToLibrary", ReplyAction="http://tempuri.org/IService1/connectToLibraryResponse")]
        System.Threading.Tasks.Task<int> connectToLibraryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listOfBorrowedItems", ReplyAction="http://tempuri.org/IService1/listOfBorrowedItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibraryClient.ServiceReference.BookExceptions), Action="http://tempuri.org/IService1/listOfBorrowedItemsBookExceptionsFault", Name="BookExceptions", Namespace="http://schemas.datacontract.org/2004/07/Library")]
        LibraryClient.ServiceReference.Book[] listOfBorrowedItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listOfBorrowedItems", ReplyAction="http://tempuri.org/IService1/listOfBorrowedItemsResponse")]
        System.Threading.Tasks.Task<LibraryClient.ServiceReference.Book[]> listOfBorrowedItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserBorrowedBooks", ReplyAction="http://tempuri.org/IService1/getUserBorrowedBooksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibraryClient.ServiceReference.BookExceptions), Action="http://tempuri.org/IService1/getUserBorrowedBooksBookExceptionsFault", Name="BookExceptions", Namespace="http://schemas.datacontract.org/2004/07/Library")]
        LibraryClient.ServiceReference.Book[] getUserBorrowedBooks(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserBorrowedBooks", ReplyAction="http://tempuri.org/IService1/getUserBorrowedBooksResponse")]
        System.Threading.Tasks.Task<LibraryClient.ServiceReference.Book[]> getUserBorrowedBooksAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBookInfo", ReplyAction="http://tempuri.org/IService1/getBookInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibraryClient.ServiceReference.BookExceptions), Action="http://tempuri.org/IService1/getBookInfoBookExceptionsFault", Name="BookExceptions", Namespace="http://schemas.datacontract.org/2004/07/Library")]
        LibraryClient.ServiceReference.Book getBookInfo(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBookInfo", ReplyAction="http://tempuri.org/IService1/getBookInfoResponse")]
        System.Threading.Tasks.Task<LibraryClient.ServiceReference.Book> getBookInfoAsync(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/borrowBook", ReplyAction="http://tempuri.org/IService1/borrowBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibraryClient.ServiceReference.BookExceptions), Action="http://tempuri.org/IService1/borrowBookBookExceptionsFault", Name="BookExceptions", Namespace="http://schemas.datacontract.org/2004/07/Library")]
        void borrowBook(int bookID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/borrowBook", ReplyAction="http://tempuri.org/IService1/borrowBookResponse")]
        System.Threading.Tasks.Task borrowBookAsync(int bookID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/giveBook", ReplyAction="http://tempuri.org/IService1/giveBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibraryClient.ServiceReference.BookExceptions), Action="http://tempuri.org/IService1/giveBookBookExceptionsFault", Name="BookExceptions", Namespace="http://schemas.datacontract.org/2004/07/Library")]
        void giveBook(int bookID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/giveBook", ReplyAction="http://tempuri.org/IService1/giveBookResponse")]
        System.Threading.Tasks.Task giveBookAsync(int bookID, int userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LibraryClient.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LibraryClient.ServiceReference.IService1>, LibraryClient.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LibraryClient.ServiceReference.Book[] listOfBooks() {
            return base.Channel.listOfBooks();
        }
        
        public System.Threading.Tasks.Task<LibraryClient.ServiceReference.Book[]> listOfBooksAsync() {
            return base.Channel.listOfBooksAsync();
        }
        
        public int connectToLibrary() {
            return base.Channel.connectToLibrary();
        }
        
        public System.Threading.Tasks.Task<int> connectToLibraryAsync() {
            return base.Channel.connectToLibraryAsync();
        }
        
        public LibraryClient.ServiceReference.Book[] listOfBorrowedItems() {
            return base.Channel.listOfBorrowedItems();
        }
        
        public System.Threading.Tasks.Task<LibraryClient.ServiceReference.Book[]> listOfBorrowedItemsAsync() {
            return base.Channel.listOfBorrowedItemsAsync();
        }
        
        public LibraryClient.ServiceReference.Book[] getUserBorrowedBooks(int userID) {
            return base.Channel.getUserBorrowedBooks(userID);
        }
        
        public System.Threading.Tasks.Task<LibraryClient.ServiceReference.Book[]> getUserBorrowedBooksAsync(int userID) {
            return base.Channel.getUserBorrowedBooksAsync(userID);
        }
        
        public LibraryClient.ServiceReference.Book getBookInfo(int bookID) {
            return base.Channel.getBookInfo(bookID);
        }
        
        public System.Threading.Tasks.Task<LibraryClient.ServiceReference.Book> getBookInfoAsync(int bookID) {
            return base.Channel.getBookInfoAsync(bookID);
        }
        
        public void borrowBook(int bookID, int userID) {
            base.Channel.borrowBook(bookID, userID);
        }
        
        public System.Threading.Tasks.Task borrowBookAsync(int bookID, int userID) {
            return base.Channel.borrowBookAsync(bookID, userID);
        }
        
        public void giveBook(int bookID, int userID) {
            base.Channel.giveBook(bookID, userID);
        }
        
        public System.Threading.Tasks.Task giveBookAsync(int bookID, int userID) {
            return base.Channel.giveBookAsync(bookID, userID);
        }
    }
}
